apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-svc
  labels:
    name: simple-webapp-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: simple-webapp
  type: ClusterIP
