apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: simple-webapp
spec:
  replicas: 3  #Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: simple-webapp
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
        - name: simple-webapp
          image: cetre/simple-webapp:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
